# Application
spring.application.name=Onboarding_Automation
server.port=8080

# Database (H2 for development)
spring.datasource.url=jdbc:h2:mem:onboarding_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA (Only for User entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PingOne Configuration
pingone.api.base-url=https://api.pingone.com/v1
pingone.api.token-url=https://auth.pingone.com/819dc7ca-6b96-4017-9fbd-be317d723035/as/token
pingone.api.client-id=977c2ff8-52ed-4504-a15a-a78db8f84a29
pingone.api.client-secret=oQaNzGMujMeRy_-k.ac8mpo1USf1GFS_jOU51.iZpO05kg8f9n.lcIxDUXWKkCvg
pingone.api.environment-id=819dc7ca-6b96-4017-9fbd-be317d723035

# TokenService properties
pingone.client-id=977c2ff8-52ed-4504-a15a-a78db8f84a29
pingone.client-secret=oQaNzGMujMeRy_-k.ac8mpo1USf1GFS_jOU51.iZpO05kg8f9n.lcIxDUXWKkCvg
pingone.auth-url=https://auth.pingone.com/819dc7ca-6b96-4017-9fbd-be317d723035/as/token
# pingone.api.client-id=REAL_CLIENT_ID
# pingone.api.client-secret=REAL_CLIENT_SECRET

# H2 Database console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [CorrID: %X{correlationId}] - %msg%n
# log to file as well
logging.file.name=app.log
logging.level.root=DEBUG

# Temporarily disable security for testing
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration